import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="flex">
          <aside
            className="w-64 bg-gray-900 text-white min-h-screen p-6"
            style={{ paddingTop: 25 }}
          >
            <h2 className="text-2xl font-bold mb-8" style={{ marginLeft: 10 }}>
              NANAS
            </h2>

            <div className="flex" style={{ marginTop: 20 }}>
              <button className=" text-gray-400 rounded-full px-4 py-2 w-[100px] h-[25px]">
                General
              </button>

              <button className=" text-gray-400 rounded-full px-4 py-2 w-[100px] h-[25px]">
                Peroject
              </button>
            </div>

            <nav
              className="flex flex-col gap-5"
              style={{ marginLeft: 20, marginTop: 20 }}
            >
              <Link href="/admin" className="hover:text-gray-300">
                Dashboard
              </Link>
              <Link href="/admin/works" className="hover:text-gray-300">
                Works
              </Link>
              <Link href="/admin/blog" className="hover:text-gray-300">
                Blog
              </Link>
              <Link href="/admin/contact" className="hover:text-gray-300">
                Contact
              </Link>
              <Link href="/admin/user" className="hover:text-gray-300">
                user
              </Link>
              <Link href="/admin/comentar" className="hover:text-gray-300">
                comentar
              </Link>
              <Link href="/admin/kategori" className="hover:text-gray-300">
                kategori
              </Link>
            </nav>
          </aside>
          <main className="w-full bg-blue-100">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
