import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Link from "next/link";
import { cookies } from "next/headers";
import { logout } from "../(auth)/login/servis";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function UserLayout({ children }) {
  const cookieStore = await cookies();
  const isLoggedIn = cookieStore.has("user_session");
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav className="bg-blue-500 h-16 flex items-center text-white">
        <div className="container flex justify-end gap-6 pr-5 ">
          <Link href="/">home</Link>
          <Link href="/works">Works</Link>
          <Link href="/blog">Blog</Link>    
          <Link href="/contact">Contact</Link>
          {isLoggedIn ? (
              <form action={logout}> 
                <button type="submit" className="hover:underline">
                  logout
                </button>
              </form>
            ) : (
              <Link href="/login">login</Link>
            )}
        </div>
      </nav>
        {children}
      </body>
    </html>
  );
}
